Learnify Functions Intro
Ada-Developers-Academy/ada-javascript-curriculum pull request #14
Opened 2020-12-03 19:17 UTC by jmaddox19

2020-12-03 22:02 UTC, CheezItMan requested changes
Pretty good I put in some suggested changes for the tests.  It's important to make the test function descriptions specific and better to make small specific tests rather than one enormous one.

2020-12-03 22:02 UTC, CheezItMan commented on 01-js-week-1/functions-intro.md
> + * Blatantly stolen from Jest (I hate mocha/chai with an irrational passion).
I love the fact that my editorial on Mocha/Chai is spreading.

2020-12-03 22:02 UTC, CheezItMan commented on 01-js-week-1/functions-intro.md
I think you need to be **very** specific to students on the exact text to print here just so they know how to pass the tests.

2020-12-03 22:02 UTC, CheezItMan commented on 01-js-week-1/functions-intro.md
> +  it('prints the strings requested, capitalization and spaces correct', () => {
Be specific

```suggestion
  it('ribbit() prints "Ribbit!" and oink() prints "Oink!"', () => {
```

2020-12-03 22:02 UTC, CheezItMan commented on 01-js-week-1/functions-intro.md
> +
This might be simpler.  You could also add tests to verify `sum` and the other variables you ask for.

```suggestion
/**
 * Blatantly stolen from Jest (I hate mocha/chai with an irrational passion).
 * 
 * This basically lets me mock a function (console.log) so I can see what they printed
 * and how many times they did so.
 * 
 * @param impl - What the real function is supposed to do.
 */
function fn (impl = () => { }) {
  const mockFn = function (...args) {
    mockFn.mock.calls.push(args);
    mockFn.mock.instances.push(this);
    try {
      const value = impl.apply(this, args); // call impl, passing the right this
      mockFn.mock.results.push({ type: 'return', value });
      return value; // return the value
    } catch (value) {
      mockFn.mock.results.push({ type: 'throw', value });
      throw value; // re-throw the error
    }
  }
  mockFn.mock = { calls: [], instances: [], results: [] };
  return mockFn;
}
  describe('testing addNums, subtractNums and multiplyNums', () => {
    let oldConsoleLog = console.log;
    // Mock console.log
    beforeEach(() => {
      console.log = fn();
    });
    
    // restore console.log
    afterEach(() => {
      console.log = oldConsoleLog;
    });
    
    it('addNums(3, 5) prints the required text and returns 8', () => {
      expect(addNums(3, 5)).to.equal(8);

      expect(console.log.mock.calls[0][0]).to.equal("The value of a is: 3");
      expect(console.log.mock.calls[1][0]).to.equal("The value of b is: 5");
    });

    it('subtractNums(3, 5) prints the required text and returns -2', () => {
      expect(subtractNums(3, 5)).to.equal(-2);

      expect(console.log.mock.calls[0][0]).to.equal("The value of a is: 3");
      expect(console.log.mock.calls[1][0]).to.equal("The value of b is: 5");
    });

    it('multiplyNums(3, 5) prints the required text and returns -2', () => {
      expect(multiplyNums(3, 5)).to.equal(15);

      expect(console.log.mock.calls[0][0]).to.equal("The value of a is: 3");
      expect(console.log.mock.calls[1][0]).to.equal("The value of b is: 5");
    });
});
```

2020-12-03 22:13 UTC, jmaddox19 commented on 01-js-week-1/functions-intro.md
My tests aren't checking for this 3rd thing, so it shouldn't be a problem...?

2020-12-03 22:18 UTC, jmaddox19 commented on 01-js-week-1/functions-intro.md
> +
Thanks for this! I agree the smaller more numerous tests are more helpful.
And can't believe I was using console.log when I didn't need to. Haha. I was so getting so used to printing things and checking the console output all the sudden.

2020-12-04 00:20 UTC, CheezItMan commented on 01-js-week-1/functions-intro.md
I mean something like, "The ribbit function should print, 'Ribbit!'"

2020-12-04 16:31 UTC, jmaddox19 commented on 01-js-week-1/functions-intro.md
I can do that but I'm not seeing how that's helpful. Is there a new concept being introduced in the third function that we need to make sure they've comprehended correctly?

In my mind it's kind of fun to let them decide the last one and just not test it.

2020-12-04 21:17 UTC, merged